config/routes.rb
CMS::Application.routes.draw do

  resources :macro_processes

  resources :user_sessions
  match '/login' => "user_sessions#new", :as => :login
  match '/logout' => "user_sessions#destroy", :as => :logout

  resources :users do
    resources :messages
  end

  get "review/show"

  get "review/edit"

  post "review/update"

  resources :comments

  resources :key_terms

  resources :critical_processes do
    member do
      post :key_term_add
      post :key_term_remove
      get :all_versions
      get :cp_members
    end
  end

  match "/dynamic_create" => "key_terms#dynamic_create", :as => :dynamic_create

  root :to => "macro_processes#index"

  resources :review, :only => [:show, :update]

  match "/usernames" => 'messages#query'
  match '/review_cps' => 'critical_processes#review_cps'

end

app/models/critical_process.rb
class CriticalProcess < ActiveRecord::Base
  belongs_to :macro_process
  has_many :categories, :dependent => :destroy
  has_many :lessons, :dependent => :destroy
  has_many :authorizations
  has_many :roles, :through => :authorizations
  has_and_belongs_to_many :key_terms
  has_one :review, :dependent => :destroy
  accepts_nested_attributes_for :categories, :reject_if => lambda { |a| a[:category_title].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :lessons, :reject_if => lambda { |a| a[:lesson_title].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :key_terms, :reject_if => lambda { |a| a[:term].blank? }

  validates_presence_of :cp_title, :message => "New CP must have a title"

  # Methods called after a CP is created
  after_create :new_cp, :create_review

  # Method called after a CP is destroyed
  before_destroy :role_check

  # Method which is called every time a new critical process is created to create the 2 new roles for that new CP
  def make_roles
    logger.debug "CALLING CREATE ROLES"
    self.roles.create :name => "#{self.cp_title} Edit", :critical_process_id => self.cp_secondary_id, :edit => true, :review => false
    self.roles.create :name => "#{self.cp_title} Review", :critical_process_id => self.cp_secondary_id, :edit => false, :review => true
  end

  # Method called after a CP is created, the method creates a new review object for that CP and assigns it to a stage 1
  def create_review
    Review.create :stage => "1", :critical_process_id => self.id
  end

  # add roles to new version of a existing cp
  def add_roles
    self.roles << Role.where(:critical_process_id => self.cp_secondary_id, :edit => true)
    self.roles << Role.where(:critical_process_id => self.cp_secondary_id, :review => true)
  end

  # Set a secondary ID to all new CPs created within the system.
  def set_secondary_id
    self.update_attribute :cp_secondary_id, self.id
  end

  # Method called whenever a CP is created within the system, it checks to see if its  entirely new one or a new version
  # if its a completely new one, it will set a secondary ID and create roles for the CP. else it will add the appropriate roles
  # to the CP
  def new_cp
    if self.cp_secondary_id.blank?
      set_secondary_id
      make_roles
    else
      add_roles
    end
  end

  # Method to retrieve all key terms that are no assigned to a CP
  def unassigned_key_terms
    KeyTerm.all - self.key_terms
  end

  # method to check if a key term already belongs to a critical process.
  def has_key_term(key_term)
    self.key_terms.include?(key_term)
  end

  # Method used to return all the users which have a edit role for the CP.
  def editors
    for role in self.roles
      if role.edit
        list_of_users = role.users
      end
    end
    return list_of_users
  end

  # Method used to return all the users which have a review role for the CP.
  def reviewers
    for role in self.roles
      if role.review
        list_of_users = role.users
      end
    end
    return list_of_users
  end

  # Method called after each CP is deleted in the system, it ensures that if the CP deleted is the last remaining version
  # of a CP, then it should delete all roles belonging to that CP and then delete the authorization rows which held the relationships.
  def role_check
    cp_roles = self.roles
    number_of_roles = cp_roles.size

    number_of_roles.times do |i|
      if cp_roles[i - 1].critical_processes.size == 1
        cp_roles[i - 1].destroy
      end
    end
    self.authorizations.each { |x| x.destroy }
  end


  # Method which would return the latest approved version of a CP.
  def latest_approved_revision
    revisions = CriticalProcess.where(:cp_secondary_id => self.cp_secondary_id)
    revisions.sort! { |x, y| y.updated_at <=> x.updated_at }

    revisions.each do |x|
      if x.review.stage == 'approved'
        return x
      end
    end
  end

  # Method takes in a a user object as a parameter and then returns an array of unique CPs which he/she is able to view.

  def self.authorized_critical_processes(user)
    critical_processes = []
    CriticalProcess.all.uniq_by { |x| x.cp_secondary_id }.each do |x|
      cps = CriticalProcess.where(:cp_secondary_id => x.cp_secondary_id)
      if user.has_access_to(cps.first) || user.is_admin
        cps = cps.sort { |x, y| y.updated_at <=> x.updated_at }
      else
        cps = cps.select { |x| x.review.stage == 'approved' if x.review && x.review.stage }
        cps = cps.sort { |x, y| y.updated_at <=> x.updated_at }
      end
      critical_processes << cps.first unless cps.blank?
    end

    return critical_processes
  end

  # Method which returns the number of unique critical processes within the system
  def self.cp_count(user)
    number_of_uniq_cps = authorized_critical_processes(user).size
    return number_of_uniq_cps
  end

end

app/controllers/critical_processes_controller.rb
class CriticalProcessesController < ApplicationController

  before_filter :require_user
  authorize_resource

  # GET /critical_processes
  # GET /critical_processes.xml
  def index
    @critical_processes = CriticalProcess.authorized_critical_processes(current_user)
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @critical_processes }
    end
  end

  # GET /critical_processes/1
  # GET /critical_processes/1.xml
  def show
    @critical_process = CriticalProcess.find(params[:id])
    @categories = @critical_process.categories
    @lessons = @critical_process.lessons
    @key_terms = @critical_process.key_terms

    authorize! :read, @critical_process

    @comments = @critical_process.review.comments.order('updated_at DESC')

    stage = @critical_process.review.stage

    if stage.to_i == 1
      @new_stage = '2'
    elsif stage.to_i == 2
      @new_stage = "3"
    elsif stage.to_i == 3
      @new_stage = "approved"
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @critical_process }
    end
  end

  # GET /critical_processes/new
  # GET /critical_processes/new.xml
  def new
    @critical_process = CriticalProcess.new
    2.times do
      category = @critical_process.categories.build
      2.times { category.capability_building_blocks.build }
    end
    authorize! :new, @critical_process
    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @critical_process }
    end
  end

  # GET /critical_processes/1/edit
  def edit
    @critical_process = CriticalProcess.find(params[:id])
    authorize! :edit, @critical_process
  end

  # POST /critical_processes
  # POST /critical_processes.xml
  def create
    @critical_process = CriticalProcess.new(params[:critical_process])

    respond_to do |format|
      if @critical_process.save
        format.html { redirect_to(@critical_process, :notice => 'New Critical Process Successfully Created.') }
        format.xml { render :xml => @critical_process, :status => :created, :location => @critical_process }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @critical_process.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /critical_processes/1
  # PUT /critical_processes/1.xml
  def update
    #here we make sure that if all key term checkbox's' are unpicked then set the key_term_ids array to empty
    params[:critical_process][:key_term_ids] ||= []
    @critical_process = CriticalProcess.find(params[:id])
    if params[:critical_process]["cp_secondary_id"].blank?
      @critical_process.update_attributes(params[:critical_process])
       UserMailer.review_edit(@critical_process).deliver
      redirect_to(@critical_process, :notice => 'Critical process was successfully updated.')
    else
      revision = CriticalProcess.create(params[:critical_process])
      revision.update_attribute :cp_secondary_id, params[:critical_process]['cp_secondary_id']
       UserMailer.new_version(revision).deliver
      redirect_to(revision, :notice => 'Revision was successfully updated.')
    end

  rescue ActiveRecord::StaleObjectError
    @critical_process.reload
    render :action => 'conflict'

  end


  # DELETE /critical_processes/1
  # DELETE /critical_processes/1.xml
  def destroy
    @critical_process = CriticalProcess.find(params[:id])
    @critical_process.destroy

    respond_to do |format|
      format.html { redirect_to(macro_processes_url) }
      format.xml { head :ok }
    end
  end

  #method to add a key term to a CP, this will be accessible through ajax (JavaScript)
  def key_term_add
    @critical_process = CriticalProcess.find(params[:id])
    @key_term = KeyTerm.find(params[:key_term])

    unless @critical_process.has_key_term(@key_term)
      @critical_process.key_terms << @key_term
      flash[:notice] = 'Key Term added successfully'
    else
      flash[:error] = 'Key term was already assigned'
    end
  end

  #method for removing key terms from a CP
  def key_term_remove
    @critical_process = CriticalProcess.find(params[:id])
    key_terms_ids = params[:key_terms]

    unless key_terms_ids.blank?
      key_terms_ids.each do |key_term_id|
        key_term = KeyTerm.find(key_term_id)
        if @critical_process.has_key_term(key_term)
          logger.info "removing key term #{key_term.id} from critical proccess"
          @critical_process.key_terms.delete(key_term)
          flash[:notice] = "Key term has been removed"
        end
      end
    end
  end

  def all_versions
    if params[:id]
      @critical_processes = CriticalProcess.where(:cp_secondary_id => params[:id]).order('updated_at DESC')
    end
  end

  def review_cps
    @critical_processes = current_user.pending_review
  end

  def cp_members
    if params[:id]
      @critical_process = CriticalProcess.find(params[:id])
      @reviewers = @critical_process.reviewers
      @editors = @critical_process.editors
    end
  end
end

app/helpers/critical_processes_helper.rb
module CriticalProcessesHelper
end

app/views/critical_processes/_authorized_show.erb
<ul class="top_content clearfix">
  <li class="heading">
    <h2><%= @critical_process.cp_title %></h2>
  </li>
  <li class="content_options">
    <% if current_user.is_admin || current_user.can_edit(@critical_process) %>
        <%= link_to 'Edit', edit_critical_process_path(@critical_process) %>
    <% end %>
    <%= link_to 'Back', macro_processes_path %>
    <%= link_to 'Show All Versions', all_versions_critical_process_path(@critical_process.cp_secondary_id) %>
    <%= link_to 'Show All Members', cp_members_critical_process_path(@critical_process.cp_secondary_id) %>
    <%= link_to 'Download (PDF)', critical_process_path(@critical_process, :format => 'pdf') %>
  </li>
</ul>

<div id="cp_intro" class="box_content">
  <h4>Introduction:</h4> <input type="checkbox" class="topic_checkbox" value="Intro"/>

  <p><%= @critical_process.cp_intro %></p>
</div>

<div id='cp_definition' class="box_content">
  <h4>Definition:</h4> <input type="checkbox" class="topic_checkbox" value="Definition"/>

  <p><%= @critical_process.cp_definition %></p>
</div>

<div id='scopes' class="clearfix">

  <h3>Scopes</h3>

  <div id='in_scope_container' class="box_content scope_box">
    <h4>In scope:</h4> <input type="checkbox" class="topic_checkbox" value="In-Scope"/>

    <p><%= @critical_process.in_scope %></p>
  </div>

  <div id='out_scope_container' class="box_content scope_box">
    <h4>Out scope:</h4> <input type="checkbox" class="topic_checkbox" value="Out-Scope"/>

    <p><%= @critical_process.out_scope %></p>
  </div>
</div>

<% if @categories %>
    <div id='cbb_definitions' class="process_table">
      <h3>Description of Categories And Underlying Capability Building Blocks</h3>
      <table border="0">
        <tr>
          <th>Categories</th>
          <th>Capability Building Blocks</th>
          <th>Description</th>
        </tr>
        <% for category in @categories %>
            <% if category.capability_building_blocks.size > 0 %>
                <tr>
                  <td class="cat" rowspan="<%= category.capability_building_blocks.size %>"><%= category.category_title %></td>
                  <td class="cbb"><%= category.capability_building_blocks.first.cbb_title %></td>
                  <td class="def"><%= category.capability_building_blocks.first.cbb_definition %></td>
                </tr>
                <% (category.capability_building_blocks - [category.capability_building_blocks.first]).each do |cbb| %>
                    <tr>
                      <td class="cbb"><%= cbb.cbb_title %></td>
                      <td class="def"><%= cbb.cbb_definition %></td>
                    </tr>
                <% end %>
            <% end %>
        <% end %>
      </table>
    </div>

    <div id="category_maturity_show" class='process_table'>
      <h3>Attributes Of Maturity Level For Each Category</h3>
      <table border="0">
        <tr>
          <th>Maturity</th>
          <% for category in @categories %>
              <th><%= category.category_title %></th>
          <% end %>
        </tr>
        <% 5.times do |i| %>
            <% level = 5 - i %>
            <tr>
              <td class="maturity_levels">Level <%= level %> Maturity</td>
              <% for category in @categories %>
                  <td class="def"><%= category.send("level_#{level}_category") %></td>
              <% end %>
            </tr>
        <% end %>
      </table>
    </div>

    <div id='CBB_maturity_show' class="process_table">
      <h3>Summary Maturity Curve For Capability Building Blocks</h3>
      <table border="0">
        <tr>
          <th>Categories</th>
          <th>CBB's</th>
          <th>Level 1</th>
          <th>Level 2</th>
          <th>Level 3</th>
          <th>Level 4</th>
          <th>Level 5</th>
        </tr>
        <% for category in @categories %>
            <% if category.capability_building_blocks.size > 0 %>
                <% logger.debug "number of capability building blocks: #{category.capability_building_blocks.size}" %>
                <tr>
                  <td class="cat" rowspan="<%= category.capability_building_blocks.size %>"><%= category.category_title %></td>
                  <td class="cbb"><%= category.capability_building_blocks.first.cbb_title %></td>
                  <td class="def"><%= category.capability_building_blocks.first.level_1_cbb %></td>
                  <td class="def"><%= category.capability_building_blocks.first.level_2_cbb %></td>
                  <td class="def"><%= category.capability_building_blocks.first.level_3_cbb %></td>
                  <td class="def"><%= category.capability_building_blocks.first.level_4_cbb %></td>
                  <td class="def"><%= category.capability_building_blocks.first.level_5_cbb %></td>
                </tr>
                <% (category.capability_building_blocks - [category.capability_building_blocks.first]).each do |cbb| %>
                    <tr>
                      <td class="cbb"><%= cbb.cbb_title %></td>
                      <td class="def"><%= cbb.level_1_cbb %></td>
                      <td class="def"><%= cbb.level_2_cbb %></td>
                      <td class="def"><%= cbb.level_3_cbb %></td>
                      <td class="def"><%= cbb.level_4_cbb %></td>
                      <td class="def"><%= cbb.level_5_cbb %></td>
                    </tr>
                <% end %>
            <% end %>
        <% end %>

      </table>
    </div>
<% end %>

<% if @lessons %>
    <div id='lessons_learned_show' class="process_table">
      <h3>Summary of Insights & Lessons Learned</h3>

      <table border="0">
        <tr>
          <th>Question</th>
          <th>Lessons Learned</th>
        </tr>
        <% for lesson in @lessons %>
            <tr>
              <td class="lesson_question">
                <%= lesson.lesson_title %>
              </td>
              <td class="lesson_def"><%= lesson.lesson_definition %></td>
            </tr>
        <% end %>
      </table>
    </div>

<% end %>

<% if @key_terms %>
    <div id="key_terms_show" class="process_table">
      <h3>Key Terms Used</h3>

      <table border="0">
        <tr>
          <th>Term/Acronym</th>
          <th>Definition</th>
        </tr>
        <% for term in @key_terms %>
            <tr>
              <td class="terms"><%= link_to term.term, term %></td>
              <td class="key_term_meaning"><%= term.meaning %></td>
            </tr>
        <% end %>
      </table>
    </div>
<% end %>

<div id="comments">

  <h3>Comments</h3>

  <!-- display all comments for this cp, in order of date added, with the user that wrote them and .  -->
  <% for comment in @comments %>

      <div class="comment">
        <div class="comment_heading">
          <p class="name"><%= link_to comment.user.name, comment.user, :class => "name_link" %></p>

          <p class="date"><%= h comment.updated_at.strftime("%H:%M %d-%m-%y") %></p>
        </div>
        <p><%= h comment.comment %></p>
        <b>Topics:</b> <%= h comment.topics %>
        <br/>
        <% if current_user.comments.include?(comment) %>
            <div id='comment_options'>
              <%= link_to "Edit", edit_comment_path(comment) %>
              <%= link_to "Delete", comment, :confirm => "Are you sure you want tod delete this comment?", :method => :delete %>
            </div>
        <% end %>
      </div>
  <% end %>

</div>

<div id="comment_form">

  <% @comment = Comment.new %>
  <%= form_for(@comment) do |f| %>

      <div class="field">
        <%= f.label :comment, "New Comment" %>
        <br/>
        <%= f.text_area :comment, :rows => 20, :cols => 60 %>
      </div>
      <div class="field">
        <%= f.hidden_field :review_id, :value => @critical_process.review.id %>
      </div>
      <div class="field">
        <%= f.hidden_field :user_id, :value => current_user.id %>
      </div>
      <div class="field">
        <%= f.hidden_field :topics, :id => "comment_topics", :value => '' %>
      </div>
      <div class="actions">
        <%= f.submit :class => "action_button" %>
      </div>
  <% end %>

</div>

<% if current_user.can_review(@critical_process) || current_user.is_admin %>
    <div id='review_form'>

      <!-- have a button that's only visible to admins and reviewers which depending on the stage of the CP allows them to approve it to the next stage. -->
      <% @review = @critical_process.review %>
      <%= form_for(@review) do |f| %>
          <% if @review.stage == 'approved' %>
              <div class="field">
                <%= f.hidden_field :stage, :value => '3' %>
              </div>
              This CP has been Approved.
              <div class="actions">
                <%= f.submit "Pull back CP to level 3", :class => 'action_button' %>
              </div>
          <% else %>
              <div class="field">
                <%= f.hidden_field :stage, :value => @new_stage %>
              </div>
              <div class="actions">
                <%= f.submit "Approve CP to level #{@new_stage}", :class => "action_button" %>
              </div>
          <% end %>
      <% end %>
    </div>
<% end %>

app/views/critical_processes/all_versions.html.erb
<% if @critical_processes.size > 1 %>
    <h2>Different versions for <%= @critical_processes.first.cp_title %></h2>
<% else %>
    <h2>This is the only available version for <%= @critical_processes.first.cp_title %></h2>
<% end %>

<table>
  <tr>
    <th>Stage</th>
    <th>Title</th>
    <th>Last Update</th>
    <th>Approval Date</th>
  </tr>

  <% @critical_processes.each do |critical_process| %>
      <tr>
        <td><%= critical_process.review.stage %></td>
        <td><%= critical_process.cp_title %></td>
        <td><%= critical_process.updated_at.strftime("%d/%m/%Y") %></td>
        <td><%= critical_process.review.updated_at.strftime("%d/%m/%Y") %></td>
        <td><%= link_to 'Show', critical_process %></td>
        <% if current_user.is_admin || current_user.can_edit(critical_process) %>
            <td><%= link_to 'Edit', edit_critical_process_path(critical_process) %></td>
            <td><%= link_to 'Destroy', critical_process, :confirm => 'Are you sure?', :method => :delete %></td>
        <% end %>
      </tr>
  <% end %>
</table>

<br/>

<% if current_user.is_admin %>
    <%= link_to 'New Critical process', new_critical_process_path, :class => 'action_button' %>
<% end %>

app/views/critical_processes/index.html.erb
<h1>IT-CMF Critical Possesses</h1>

<table>
  <tr>
    <% if current_user.authorised %>
        <th>Stage</th>
    <% end %>
    <th>Secondary ID</th>
    <th>Title</th>
  </tr>

  <% @critical_processes.each do |critical_process| %>
      <tr>

        <% if current_user.authorised %>
            <td><%= critical_process.review.stage %></td>
        <% end %>
        <td><%= critical_process.cp_secondary_id %></td>
        <td><%= critical_process.cp_title %></td>

        <td><%= link_to 'Show', critical_process %></td>
        <% if current_user.has_access_to(critical_process) || current_user.is_admin %>
            <td><%= link_to 'Edit', edit_critical_process_path(critical_process) %></td>
            <td><%= link_to 'show all versions', all_versions_critical_process_path(critical_process.cp_secondary_id) %></td>
            <td><%= link_to 'Destroy', critical_process, :confirm => 'Are you sure?', :method => :delete %></td>
        <% end %>
      </tr>
  <% end %>
</table>

<br/>
<% if current_user.is_admin %>
    <%= link_to 'New Critical process', new_critical_process_path%>
<% end %>

app/views/critical_processes/new.html.erb
<h2>New Critical Process</h2>

<%= render 'form' %>

<%= link_to 'Back', macro_processes_path %>

app/views/critical_processes/review_cps.erb
<% if @critical_processes.size > 0 %>
    <h2>Critical Processes Under Review: <%= @critical_processes.size %></h2>
    <table>
      <tr>
        <th>Stage</th>
        <th>Title</th>
        <th>Last Update</th>
        <th>Last Approval</th>
      </tr>

      <% @critical_processes.each do |critical_process| %>
          <tr>
            <td><%= critical_process.review.stage %></td>
            <td><%= critical_process.cp_title %></td>
            <td><%= critical_process.updated_at.strftime("%d/%m/%Y") %></td>
            <td><%= critical_process.review.updated_at.strftime("%d/%m/%Y") %></td>
            <td><%= link_to 'Show', critical_process %></td>
            <% if can? :edit, critical_process %>
                <td><%= link_to 'Edit', edit_critical_process_path(critical_process) %></td>
                <td><%= link_to 'Destroy', critical_process, :confirm => 'Are you sure?', :method => :delete %></td>
            <% end %>
          </tr>
      <% end %>
    </table>
<% else %>
    <h3>No Critical Processes Under Review</h3>
<% end %>

app/views/critical_processes/show.html.erb
<% if current_user.is_admin || current_user.has_access_to(@critical_process) %>
    <%= render 'authorized_show' %>
<% else %>
    <ul class="top_content clearfix">
      <li class="heading">
        <h2><%= @critical_process.cp_title %></h2>
      </li>
      <li class="content_options">
        <%= link_to 'Back', macro_processes_path %>
        <%= link_to 'Download (PDF)', critical_process_path(@critical_process, :format => 'pdf') %>
      </li>
    </ul>

    <div id="cp_intro" class="box_content">
      <h4>Introduction:</h4>

      <p><%= @critical_process.cp_intro %></p>
    </div>

    <div id='cp_definition' class="box_content">
      <h4>Definition:</h4>

      <p><%= @critical_process.cp_definition %></p>
    </div>

    <div id='scopes' class="clearfix">

      <h3>Scopes</h3>

      <div id='in_scope_container' class="box_content scope_box">
        <h4>In scope:</h4>

        <p><%= @critical_process.in_scope %></p>
      </div>

      <div id='out_scope_container' class="box_content scope_box">
        <h4>Out scope:</h4>

        <p><%= @critical_process.out_scope %></p>
      </div>
    </div>

    <% if @categories %>
        <div id='cbb_definitions' class="process_table">
          <h3>Description of Categories And Underlying Capability Building Blocks</h3>
          <table border="0">
            <tr>
              <th>Categories</th>
              <th>Capability Building Blocks</th>
              <th>Description</th>
            </tr>
            <% for category in @categories %>
                <% if category.capability_building_blocks.size > 0 %>
                    <tr>
                      <td class="cat" rowspan="<%= category.capability_building_blocks.size %>"><%= category.category_title %></td>
                      <td class="cbb"><%= category.capability_building_blocks.first.cbb_title %></td>
                      <td class="def"><%= category.capability_building_blocks.first.cbb_definition %></td>
                    </tr>
                    <% (category.capability_building_blocks - [category.capability_building_blocks.first]).each do |cbb| %>
                        <tr>
                          <td class="cbb"><%= cbb.cbb_title %></td>
                          <td class="def"><%= cbb.cbb_definition %></td>
                        </tr>
                    <% end %>
                <% end %>
            <% end %>
          </table>
        </div>

        <div id="category_maturity_show" class='process_table'>
          <h3>Attributes Of Maturity Level For Each Category</h3>
          <table border="0">
            <tr>
              <th>Maturity</th>
              <% for category in @categories %>
                  <th><%= category.category_title %></th>
              <% end %>
            </tr>
            <% 5.times do |i| %>
                <% level = 5 - i %>
                <tr>
                  <td class="maturity_levels">Level <%= level %> Maturity</td>
                  <% for category in @categories %>
                      <td class="def"><%= category.send("level_#{level}_category") %></td>
                  <% end %>
                </tr>
            <% end %>
          </table>
        </div>

        <div id='CBB_maturity_show' class="process_table">
          <h3>Summary Maturity Curve For Capability Building Blocks</h3>
          <table border="0">
            <tr>
              <th>Categories</th>
              <th>CBB's</th>
              <th>Level 1</th>
              <th>Level 2</th>
              <th>Level 3</th>
              <th>Level 4</th>
              <th>Level 5</th>
            </tr>
            <% for category in @categories %>
                <% if category.capability_building_blocks.size > 0 %>
                    <% logger.debug "number of capability building blocks: #{category.capability_building_blocks.size}" %>
                    <tr>
                      <td class="cat" rowspan="<%= category.capability_building_blocks.size %>"><%= category.category_title %></td>
                      <td class="cbb"><%= category.capability_building_blocks.first.cbb_title %></td>
                      <td class="def"><%= category.capability_building_blocks.first.level_1_cbb %></td>
                      <td class="def"><%= category.capability_building_blocks.first.level_2_cbb %></td>
                      <td class="def"><%= category.capability_building_blocks.first.level_3_cbb %></td>
                      <td class="def"><%= category.capability_building_blocks.first.level_4_cbb %></td>
                      <td class="def"><%= category.capability_building_blocks.first.level_5_cbb %></td>
                    </tr>
                    <% (category.capability_building_blocks - [category.capability_building_blocks.first]).each do |cbb| %>
                        <tr>
                          <td class="cbb"><%= cbb.cbb_title %></td>
                          <td class="def"><%= cbb.level_1_cbb %></td>
                          <td class="def"><%= cbb.level_2_cbb %></td>
                          <td class="def"><%= cbb.level_3_cbb %></td>
                          <td class="def"><%= cbb.level_4_cbb %></td>
                          <td class="def"><%= cbb.level_5_cbb %></td>
                        </tr>
                    <% end %>
                <% end %>
            <% end %>

          </table>
        </div>
    <% end %>

    <% if @lessons %>
        <div id='lessons_learned_show' class="process_table">
          <h3>Summary of Insights & Lessons Learned</h3>

          <table border="0">
            <tr>
              <th>Question</th>
              <th>Lessons Learned</th>
            </tr>
            <% for lesson in @lessons %>
                <tr>
                  <td class="lesson_question">
                    <%= lesson.lesson_title %>
                  </td>
                  <td class="lesson_def"><%= lesson.lesson_definition %></td>
                </tr>
            <% end %>
          </table>
        </div>

    <% end %>

    <% if @key_terms %>
        <div id="key_terms_show" class="process_table">
          <h3>Key Terms Used</h3>

          <table border="0">
            <tr>
              <th>Term/Acronym</th>
              <th>Definition</th>
            </tr>
            <% for term in @key_terms %>
                <tr>
                  <td class="terms"><%= link_to term.term, term %></td>
                  <td class="key_term_meaning"><%= term.meaning %></td>
                </tr>
            <% end %>
          </table>
        </div>
    <% end %>
<% end %>