config/routes.rb
CMS::Application.routes.draw do

  resources :macro_processes

  resources :user_sessions
  match '/login' => "user_sessions#new", :as => :login
  match '/logout' => "user_sessions#destroy", :as => :logout

  resources :users do
    resources :messages
  end

  get "review/show"

  get "review/edit"

  post "review/update"

  resources :comments

  resources :key_terms

  resources :critical_processes do
    member do
      post :key_term_add
      post :key_term_remove
      get :all_versions
      get :cp_members
    end
  end

  match "/dynamic_create" => "key_terms#dynamic_create", :as => :dynamic_create

  root :to => "macro_processes#index"

  resources :review, :only => [:show, :update]

  match "/usernames" => 'messages#query'
  match '/review_cps' => 'critical_processes#review_cps'

end

app/models/critical_process.rb
class CriticalProcess < ActiveRecord::Base
  belongs_to :macro_process
  has_many :categories, :dependent => :destroy
  has_many :lessons, :dependent => :destroy
  has_many :authorizations
  has_many :roles, :through => :authorizations
  has_and_belongs_to_many :key_terms
  has_one :review, :dependent => :destroy
  accepts_nested_attributes_for :categories, :reject_if => lambda { |a| a[:category_title].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :lessons, :reject_if => lambda { |a| a[:lesson_title].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :key_terms, :reject_if => lambda { |a| a[:term].blank? }

  validates_presence_of :cp_title, :message => "New CP must have a title"

  # Methods called after a CP is created
  after_create :new_cp, :create_review

  # Method called after a CP is destroyed
  before_destroy :role_check

  # Method which is called every time a new critical process is created to create the 2 new roles for that new CP
  def make_roles
    logger.debug "CALLING CREATE ROLES"
    self.roles.create :name => "#{self.cp_title} Edit", :critical_process_id => self.cp_secondary_id, :edit => true, :review => false
    self.roles.create :name => "#{self.cp_title} Review", :critical_process_id => self.cp_secondary_id, :edit => false, :review => true
  end

  # Method called after a CP is created, the method creates a new review object for that CP and assigns it to a stage 1
  def create_review
    Review.create :stage => "1", :critical_process_id => self.id
  end

  # add roles to new version of a existing cp
  def add_roles
    self.roles << Role.where(:critical_process_id => self.cp_secondary_id, :edit => true)
    self.roles << Role.where(:critical_process_id => self.cp_secondary_id, :review => true)
  end

  # Set a secondary ID to all new CPs created within the system.
  def set_secondary_id
    self.update_attribute :cp_secondary_id, self.id
  end

  # Method called whenever a CP is created within the system, it checks to see if its  entirely new one or a new version
  # if its a completely new one, it will set a secondary ID and create roles for the CP. else it will add the appropriate roles
  # to the CP
  def new_cp
    if self.cp_secondary_id.blank?
      set_secondary_id
      make_roles
    else
      add_roles
    end
  end

  # Method to retrieve all key terms that are no assigned to a CP
  def unassigned_key_terms
    KeyTerm.all - self.key_terms
  end

  # method to check if a key term already belongs to a critical process.
  def has_key_term(key_term)
    self.key_terms.include?(key_term)
  end

  # Method used to return all the users which have a edit role for the CP.
  def editors
    for role in self.roles
      if role.edit
        list_of_users = role.users
      end
    end
    return list_of_users
  end

  # Method used to return all the users which have a review role for the CP.
  def reviewers
    for role in self.roles
      if role.review
        list_of_users = role.users
      end
    end
    return list_of_users
  end

  # Method called after each CP is deleted in the system, it ensures that if the CP deleted is the last remaining version
  # of a CP, then it should delete all roles belonging to that CP and then delete the authorization rows which held the relationships.
  def role_check
    cp_roles = self.roles
    number_of_roles = cp_roles.size

    number_of_roles.times do |i|
      if cp_roles[i - 1].critical_processes.size == 1
        cp_roles[i - 1].destroy
      end
    end
    self.authorizations.each { |x| x.destroy }
  end


  # Method which would return the latest approved version of a CP.
  def latest_approved_revision
    revisions = CriticalProcess.where(:cp_secondary_id => self.cp_secondary_id)
    revisions.sort! { |x, y| y.updated_at <=> x.updated_at }

    revisions.each do |x|
      if x.review.stage == 'approved'
        return x
      end
    end
  end

  # Method takes in a a user object as a parameter and then returns an array of unique CPs which he/she is able to view.

  def self.authorized_critical_processes(user)
    critical_processes = []
    CriticalProcess.all.uniq_by { |x| x.cp_secondary_id }.each do |x|
      cps = CriticalProcess.where(:cp_secondary_id => x.cp_secondary_id)
      if user.has_access_to(cps.first) || user.is_admin
        cps = cps.sort { |x, y| y.updated_at <=> x.updated_at }
      else
        cps = cps.select { |x| x.review.stage == 'approved' if x.review && x.review.stage }
        cps = cps.sort { |x, y| y.updated_at <=> x.updated_at }
      end
      critical_processes << cps.first unless cps.blank?
    end

    return critical_processes
  end

  # Method which returns the number of unique critical processes within the system
  def self.cp_count(user)
    number_of_uniq_cps = authorized_critical_processes(user).size
    return number_of_uniq_cps
  end

end

app/models/key_term.rb
class KeyTerm < ActiveRecord::Base
  has_and_belongs_to_many :critical_processes

  # Ensure that any new created key term is unique
  validates :term, :uniqueness => true,
                   :presence => true
  # Ensure that all new created key terms have a meaning.
  validates_presence_of :meaning

end

app/controllers/key_terms_controller.rb
class KeyTermsController < ApplicationController

  before_filter :require_user
  # GET /key_terms
  # GET /key_terms.xml
  def index
    @key_terms = KeyTerm.scoped.order('term').page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @key_terms }
    end
  end

  # GET /key_terms/1
  # GET /key_terms/1.xml
  def show
    @key_term = KeyTerm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @key_term }
    end
  end

  # GET /key_terms/new
  # GET /key_terms/new.xml
  def new
    @key_term = KeyTerm.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @key_term }
    end
  end

  # GET /key_terms/1/edit
  def edit
    @key_term = KeyTerm.find(params[:id])
  end

  # POST /key_terms
  # POST /key_terms.xml
  def create
    @key_term = KeyTerm.new(params[:key_term])

    respond_to do |format|
      if @key_term.save
        format.html { redirect_to(@key_term, :notice => 'Key term was successfully created.') }
        format.xml  { render :xml => @key_term, :status => :created, :location => @key_term }
        format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @key_term.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /key_terms/1
  # PUT /key_terms/1.xml
  def update
    @key_term = KeyTerm.find(params[:id])

    respond_to do |format|
      if @key_term.update_attributes(params[:key_term])
        format.html { redirect_to(@key_term, :notice => 'Key term was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @key_term.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /key_terms/1
  # DELETE /key_terms/1.xml
  def destroy
    @key_term = KeyTerm.find(params[:id])
    @key_term.destroy

    respond_to do |format|
      format.html { redirect_to(key_terms_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/key_terms_helper.rb
module KeyTermsHelper
end

app/views/key_terms/_form.html.erb
<%= form_for(@key_term ) do |f| %>
  <% if @key_term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@key_term.errors.count, "error") %> prohibited this key_term from being saved:</h2>

      <ul>
      <% @key_term.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :term %><br />
    <%= f.text_field :term %>
  </div>
  <div class="field">
    <%= f.label :meaning %><br />
    <%= f.text_area :meaning %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'action_button' %>
  </div>
<% end %>

app/views/key_terms/create.js.erb
var key_term_line = "";
key_term_line += "<%= escape_javascript( check_box_tag 'critical_process[key_term_ids][]', "#{@key_term.id.to_i}", true, :id => 'critical_process_key_term_ids_' ) %>";
key_term_line += "<%= escape_javascript(@key_term.term )%>";

$("#new_key_term_dialog").dialog("close");
$("#key_term_list").append($("<li></li>").html(key_term_line));
$('#key_term_term').val("");
$('#key_term_meaning').val("");

app/views/key_terms/edit.html.erb
<h2>Edit Key Term</h2>
<%= render 'form' %>

<%= link_to 'Show', @key_term %> |
<%= link_to 'Back', key_terms_path %>

app/views/key_terms/index.html.erb
<h2>Key Terms</h2>


<%= paginate @key_terms %>

<table>
  <tr>
    <th>Term</th>
    <th>Meaning</th>
  </tr>

  <% @key_terms.each do |key_term| %>
      <tr>
        <td class="key_term"><%= link_to key_term.term, key_term %></td>
        <td class="key_term_meaning"><%= key_term.meaning[0..70] %></td>
        <td><%= link_to 'Show', key_term %></td>
        <% if current_user.authorised %>
            <td><%= link_to 'Edit', edit_key_term_path(key_term) %></td>
            <td><%= link_to 'Destroy', key_term, :confirm => 'Are you sure?', :method => :delete %></td>
        <% end %>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Key term', new_key_term_path, :class => 'action_button' %>

app/views/key_terms/new.html.erb
<h2>New Key Term</h2>
    <%= render 'form' %>
    <%= link_to 'Back', key_terms_path %>

app/views/key_terms/show.html.erb
<p id="notice"><%= notice %></p>


<ul class="top_content clearfix">
  <li class="heading">

    <h2>Key Term: <span class="key_term"><%= @key_term.term %></span></h2>
  </li>
  <li class="content_options">

    <%= link_to 'Edit', edit_key_term_path(@key_term) %>
    <%= link_to 'Back', key_terms_path %>


  </li>


</ul>


<p>
  <%= @key_term.meaning %>
</p>