config/routes.rb
CMS::Application.routes.draw do

  resources :macro_processes

  resources :user_sessions
  match '/login' => "user_sessions#new", :as => :login
  match '/logout' => "user_sessions#destroy", :as => :logout

  resources :users do
    resources :messages
  end

  get "review/show"

  get "review/edit"

  post "review/update"

  resources :comments

  resources :key_terms

  resources :critical_processes do
    member do
      post :key_term_add
      post :key_term_remove
      get :all_versions
      get :cp_members
    end
  end

  match "/dynamic_create" => "key_terms#dynamic_create", :as => :dynamic_create

  root :to => "macro_processes#index"

  resources :review, :only => [:show, :update]

  match "/usernames" => 'messages#query'
  match '/review_cps' => 'critical_processes#review_cps'

end

app/controllers/macro_processes_controller.rb
class MacroProcessesController < ApplicationController

  before_filter :require_user

  # GET /macro_processes
  # GET /macro_processes.xml
  def index
    @macro_processes = MacroProcess.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @macro_processes }
    end
  end

  # GET /macro_processes/1
  # GET /macro_processes/1.xml
  def show
    @macro_process = MacroProcess.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @macro_process }
    end
  end

  # GET /macro_processes/new
  # GET /macro_processes/new.xml
  def new
    @macro_process = MacroProcess.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @macro_process }
    end
  end

  # GET /macro_processes/1/edit
  def edit
    @macro_process = MacroProcess.find(params[:id])
  end

  # POST /macro_processes
  # POST /macro_processes.xml
  def create
    @macro_process = MacroProcess.new(params[:macro_process])

    respond_to do |format|
      if @macro_process.save
        format.html { redirect_to(@macro_process, :notice => 'Macro process was successfully created.') }
        format.xml  { render :xml => @macro_process, :status => :created, :location => @macro_process }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @macro_process.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /macro_processes/1
  # PUT /macro_processes/1.xml
  def update
    @macro_process = MacroProcess.find(params[:id])

    respond_to do |format|
      if @macro_process.update_attributes(params[:macro_process])
        format.html { redirect_to(@macro_process, :notice => 'Macro process was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @macro_process.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /macro_processes/1
  # DELETE /macro_processes/1.xml
  def destroy
    @macro_process = MacroProcess.find(params[:id])
    @macro_process.destroy

    respond_to do |format|
      format.html { redirect_to(macro_processes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/macro_processes_helper.rb
module MacroProcessesHelper
end

app/views/macro_processes/_form.html.erb
<%= form_for(@macro_process) do |f| %>
  <% if @macro_process.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@macro_process.errors.count, "error") %> prohibited this macro_process from being saved:</h2>

      <ul>
      <% @macro_process.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'action_button' %>
  </div>
<% end %>

app/views/macro_processes/edit.html.erb
<h2>Editing <%= @macro_process.name %></h2>

<%= render 'form' %>

<%= link_to 'Show', @macro_process %> |
<%= link_to 'Back', macro_processes_path %>

app/views/macro_processes/index.html.erb
<% if current_user.is_admin %>
<%= link_to 'New Critical Process', new_critical_process_path, :class => "action_button", :id => "mac_process" %>
<% end %>
<div id="macro_processes_container" class="clearfix">
<% @macro_processes.each_with_index do |macro_process, index| %>
    <div id="container_<%= index.to_s %>" class="index_macro_container">

      <ul>
      <li class="macro_heading"><h3><%= link_to macro_process.name, macro_process, :class => 'macro_heading' %></h3></li>
      <% macro_process.authorized_critical_processes(current_user).each do |cp| %>

          <li class="pro_link"><%= link_to cp.cp_title, cp %></li>
      <% end %>
      </ul>
    </div>
<% end %>
</div>

app/views/macro_processes/new.html.erb
<h1>New macro_process</h1>

<%= render 'form' %>

<%= link_to 'Back', macro_processes_path %>

app/views/macro_processes/show.html.erb
<p id="notice"><%= notice %></p>
<ul class="top_content clearfix">
  <li class="heading">
    <h2><%= @macro_process.name %></h2>
  </li>

  <li class="content_options">
    <% if current_user.is_admin %>
        <a href="<%= "/critical_processes/new?macro_process=#{@macro_process.id}" %>">Create New Critical Process</a>
        <%= link_to 'Edit', edit_macro_process_path(@macro_process) %>
    <% end %>
    <%= link_to 'Back', macro_processes_path %>
  </li>
</ul>
<% if @macro_process.authorized_critical_processes(current_user).size > 0 %>
    <div class="critical_processes">
      <div id="container_<%= @macro_process.get_macro_style_number %>" class="index_macro_container">
        <ul>
          <li class="macro_heading"><h3><%= link_to @macro_process.name, @macro_process %></h3></li>
          <% @macro_process.authorized_critical_processes(current_user).each do |cp| %>

              <li class="pro_link"><%= link_to cp.cp_title, cp %></li>
          <% end %>
        </ul>
      </div>
    </div>

<% else %>
    <h3>Sorry But This Macro Process Has No Underlying Critical Processes </h3>
<% end %>